stages:
  - build-and-test

build-and-test:
  stage: build-and-test
  image: openjdk:10.0.2-jdk-slim
  script:
    - chmod +x ./gradlew
    - ./gradlew build jacocoTestReport
  artifacts:
    when: always
    paths:
      - build/reports/
  only:
    - master
